microservice: ## general service details
  name: grade-submission-portal
  namespace: grade-submission-namespace
  replicas: 1

workload:  ## container specific configurations
  image: rslim087/kubernetes-course-grade-submission-portal
  port: 5001
  resources:
    memory: "128Mi"
    cpu: "200m"
  livenessDelay: 15

env:   ## environment variables
  GRADE_SERVICE_HOST: grade-submission-api


## upgrade to include host for ingress