apiVersion: v1
kind: Service
metadata:
  name: grade-submission-api
  namespace: grade-submission-namespace
spec:
  selector:
    app.kubernetes.io/instance: grade-submission-api
  ports:
    - port: 3000
      targetPort: 3000

