apiVersion: v1
kind: Pod
metadata:
  name: grade-submission-portal # what is it?
  namespace: grade-submission-namespace
  labels:
    app.kubernetes.io/name: grade-submission # ?
    app.kubernetes.io/component: frontend # ?
    app.kubernetes.io/instance: grade-submission-portal
spec:
  containers:
    - name: grade-submission-portal
      image: rslim087/kubernetes-course-grade-submission-portal
      env:
        - name: GRADE_SERVICE_HOST
          value: grade-submission-api
      resources:
        requests: # minimum requirements to run resources
          memory: "128Mi" # memory can't be throttled
          cpu: "200m" # memory can't be throttled
        limits:
          memory: "128Mi" # always set a memory limit
      ports:
        - containerPort: 5001
