 package com.spring_tutorial.content_calendar.controller;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.spring_tutorial.content_calendar.model.Content;
import com.spring_tutorial.content_calendar.repository.ContentCollectionRepository;

import jakarta.validation.Valid;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;



@RestController
@RequestMapping("/api/content")
public class ContentController {

    private final ContentCollectionRepository repo;

    public ContentController(ContentCollectionRepository r) {
        this.repo = r;
    }

    @GetMapping
    public List<Content> findAll() {
        return repo.findAll();
    }

    @GetMapping("/{id}")
    public Optional<Content> findById(@PathVariable Integer id) {
        return repo.findById(id);
    }

    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    public void create(@Valid @RequestBody Content content) {
    content = new Content(
        null, // ID will be autogenerated
        content.title(),
        content.desc(),
        content.status(),
        content.contentType(),
        LocalDateTime.now(), // Set dateCreated
        null, // dateUpdated can be null at creation
        content.url()
    );
        repo.save(content);
    }
    
    
    
}