microservice:   ## general service details 
  name: grade-submission-api
  namespace: grade-submission-namespace
  replicas: 2

workload:   ## container specific configurations
  image: rslim087/kubernetes-course-grade-submission-api:stateless-v3
  port: 3000
  resources:
    memory: "128Mi"
    cpu: "128m"
  livenessDelay: 15

secrets:  ## sensitive data
  MONGODB_URI: 'mongodb://mongodb:27017'
