apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.microservice.name }}-secret
  namespace: {{ .Values.microservice.namespace }}
type: Opaque
stringData:
  MONGODB_URI: {{ .Values.secrets.MONGODB_URI }}   ## assumes this is base64 encoded, and interprets as admin
