apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: grade-submission-namespace
spec:
  selector:
    app.kubernetes.io/instance: mongodb
  ports:
  - port: 27017
    targetPort: 27017
