apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: grade-submission-namespace
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: 'YWRtaW4='   ## assumes this is base64 encoded, and interprets as admin
  MONGO_INITDB_ROOT_PASSWORD: 'cGFzc3dvcmQxMjM=' ## assumes this is base64 encoded, and interprets as password123
